%YAML 1.2
---

#CAMERA
UseXtionGen       : 1
Fps               : 30
ImgHeight         : 240
ImgWidth          : 320
InnerCx           : 160.5912
InnerCy           : 120.4792
InnerFx           : 253.0589
InnerFy           : 254.1649
DepthScale        : 10.0

#VO
FeatureNum        : 1200
ScaleFactor       : 1.2
LevelNum          : 8
IniThFAST         : 20
MinThFAST         : 7

#Map
VoxelSize        : 0.05

#FeatureMatching
Threshold         : 50
NNRatio           : 0.6

#KeyFrame
MaxMatchPointThres: 80
MinMatchPointThres: 50
MaxFramesBetween  : 40
MinFramesBetween  : 20

#Local
WindowSize        : 20
KFInterval        : 8

#IMU
IMUDevNum         : 0
BaudRate          : 460800
MaxBufferLen      : 100
DataLen           : 32

#Optimizer
IMUGain           : 5000.0
Chi2Thresh        : 12.8
ZAxisInfo         : 0.5
LocalChi2Thresh   : 2000.0

